/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


#define SECRET
#define THINGNAME "HRRYP964" // Replace with your AWS IoT core Thing Name

const char AWS_IOT_ENDPOINT[] = "a345vu73g6bbpf-ats.iot.us-east-1.amazonaws.com"; // Your AWS IoT Core Endpoint

// Amazon Root CA 1
static const char AWS_CERT_CA[] = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char AWS_CERT_CRT[] = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUWoCjzRxmdb8sKwc76APs5PJ8ecIwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTI2MDIyNjIyMjQx
M1oXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKnU3l3YaP+1vr7MF+Zk
t7d2LH2MI4dzLF3fPnk8KuIlUaswVAmE8kkjhlmyJynh78BBk6O5BwlVJr0U6gap
R4y4Ywq8DqS/hU8kKqCY2D5Vwfk0mwm7dpNndKplihUCP8rxAgHoyfH74DGCh1/h
aBqQOFtdOCuH2zM0EW+rNhifk74bQDiEhETv/lvq3ZW+Q40uB9aJtae4ok39mNXG
YQei30dDE6qUuZ4dc7MVK6YMJ8y+Qw4X8sYwf0H722RjvrJO1V+ByZqu7OD3bOtn
ruNYI2dxWOOpIrGXsxLp1AvvwhvN7cuZbijhrmjLKzPIN7QP4T7pUyVJ2ppp75nK
yOECAwEAAaNgMF4wHwYDVR0jBBgwFoAUOHjV+W8V8AStaZ5i9pcXPidvvckwHQYD
VR0OBBYEFCQ6zxg263HOj0Mf1d8m7fZNqzWZMAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQALHD3mRZWjxbfN2Xu7yfIUTgXM
mc0+wuBDsICVuBHWn/XqTl6EH0JZCybNyCEXGeFC4sYvZkkpXkqPajZQVB5NGNLr
k2NTfknX7tqYv3llTMBr0WtLVkGL2p7hbrgmpaBiEpEIxVDNcDma0BmKRrYKUBM4
Ibe5YKM/YgDIhS5Bbo4IjH0Flph+EA+jsnaAAPU6NLd53lYgvbusmvx05xOUbmHT
N0KUE+xqm3nwqcuxvyI6pGkWUV2px5vTAceOS9EFjh7+p9g6PCCGNdO0mSSl/hWL
I9qxa4V/CKHXxS0qQ2412H66fUfb/Pyh56KAier1NPdZdWUJcYR4xkkG9qE2
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAqdTeXdho/7W+vswX5mS3t3YsfYwjh3MsXd8+eTwq4iVRqzBU
CYTySSOGWbInKeHvwEGTo7kHCVUmvRTqBqlHjLhjCrwOpL+FTyQqoJjYPlXB+TSb
Cbt2k2d0qmWKFQI/yvECAejJ8fvgMYKHX+FoGpA4W104K4fbMzQRb6s2GJ+TvhtA
OISERO/+W+rdlb5DjS4H1om1p7iiTf2Y1cZhB6LfR0MTqpS5nh1zsxUrpgwnzL5D
DhfyxjB/QfvbZGO+sk7VX4HJmq7s4Pds62eu41gjZ3FY46kisZezEunUC+/CG83t
y5luKOGuaMsrM8g3tA/hPulTJUnammnvmcrI4QIDAQABAoIBAQCiQHDBj8OgqW42
sp4Syx6J9CjFOWGoQmycsm/pO4Zsz+Kafm2LOqyPG5V7lCy+YtC/COeYf2ktjWCZ
PKXo/0kQNAjLdKc41pDx70eabuwJgbzz7UJBpgu/ABQBx0iIkcGIjYCxekmVGmIy
atYS0DK5ThfJkeHcFMtiu9f8q8He+uergvoXT5rHFsj8GTr4jfunVL6oS2vyhcDm
IAZ7VDFO3PL8U6KH9+PxZCj0ALDfOhnzATBlx9wnSdbyEwGzBjEDF7u242BuHLvZ
dRFXN/SCkJx99dZsOUttdYenMNpqSHzYb2y2OKqeunUKqR07UR3oYnOFGx2ckPwc
8lrf84HBAoGBANG3maVPRzvKxyduem9MvDkDyLZxKEzmLw6EOPLPQte1ahYTIbC/
entypROuiurvARX+BUXTGhNGX/o4DmUzVY8T49kUFXAIrEJrVxgQNsEJ5epI9IeB
E+o5hmihPCXBeHfmnUVxZzvxXOBsExz4AwwWNug164bO4T4PS2Dyt7VNAoGBAM9P
2KNjy2WYCH1bf0jf7Ng5a3FdfTHgyMYxnd58BxdIpSUDf0iKNRj9h4rqWXaSRAc0
hIrI1bsQg0BAVOfyUbsR7ZUmte6z5H/x1iCA8M2vjqbETFt99jjAjDEXYdI5xbbU
9TyAtKui9vYZxb6y548thaVh92zT0nj/LbPRQoflAoGAX6qpZEet7xCpmMtE/tC6
bCfVv6QPBkVa4fxfHiR+EXioVDmV/NLcRMQfmcLdjB5LGIUwUpHiKzjHP5Wiu3eX
aBVisvv+a4UJT6M3r7p1v8mMIDv3kHjJZOeo8MHcdjyzf76rr6nztdx8ycODVIuu
mCzqDzPJpU1qYq0HbcpLE2ECgYEAkiS/m68mG6Bpm7V8rWruFB+mVmyJbTgBUXZ4
y/azKP7VLJqiiAimFc/kVVGPb778pfen2A5sXUruu8SeFkUEyNOCoLqBVp0KYAej
45YCK32vGnEXQwgxIyDZs2HAW+rOLm1B1D0HIFfpsOPKOvzzsENvC39cZSOOJC3/
kdvbAuECgYBtAZBRN+rvXsuhfXRUFA3ZCasTTlf+hoGB0qVOcQxtf3OyWDveEv5s
YJNEjjy0Seix7zlUL2Ai/sejEXMnYSaKt84eqCs6r5G7BCKcr9KvZiuvhTBDFe5l
0IFJvje1Jx8NV3+WClkogY4EmKj3hZuk8uuVpmye9az5z/DRT8tvVg==
-----END RSA PRIVATE KEY-----
)KEY";
